version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-cloud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sim7geg4nbtk"
s3_prefix = "resume-cloud"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
